name: CI for VSCode Extension

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install
          # 安装 @types/node 以确保 TypeScript 类型定义可用
          yarn add @types/node --dev

      - name: Ensure TypeScript Configuration
        run: |
          # 检查 tsconfig.json 是否存在
          if [ -f "tsconfig.json" ]; then
            echo "Ensuring tsconfig.json contains correct lib options..."
            # 检查并添加 "dom" 和 "es2015" 到 lib 配置中
            if ! grep -q '"dom"' tsconfig.json; then
              sed -i 's/"lib": \[/& "dom", /' tsconfig.json
            fi
            if ! grep -q '"es2015"' tsconfig.json; then
              sed -i 's/"lib": \[/& "es2015", /' tsconfig.json
            fi
          else
            echo "tsconfig.json not found."
          fi

      - name: Lint
        run: yarn run lint

      - name: Compile tests and source code
        run: yarn run pretest

      - name: Run tests
        run: yarn run test
